[project]
name = "amazon-cli"
version = "0.1.0"
description = "Amazon shopping automation using Selenium"
authors = [
    {name = "ariya-sequoiaat",email = "ariya@sequoiaat.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "selenium (>=4.28.1,<5.0.0)",
    "webdriver-manager (>=4.0.2,<5.0.0)",
    "pytest (>=8.3.4,<9.0.0)",
    "pytest-selenium (>=4.1.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
